# fly.toml app configuration file for songsymmetry
app = "songsymmetry"
primary_region = "sin"

[build]
dockerfile = "Dockerfile"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = "suspend"
auto_start_machines = true
min_machines_running = 0

[env]
NODE_ENV = "production"
# Other environment variables are set from secrets

[[vm]]
memory = "1gb"
cpu_kind = "shared"
cpus = 1
