"use client";

import { useState, useEffect, useCallback } from 'react';
import { Track, Playlist } from "@spotify/web-api-ts-sdk";
import { useToast } from "@/hooks/use-toast";
import { useRouter } from "next/navigation";
import { useSpotify } from "./useSpotify";
import { useMemo } from 'react';

export type SongRecommendation = {
  source: Track;
  recommendation: {
    tracks: Track[];
    seeds: {
      id: string;
      href: string;
      type: string;
      initialPoolSize: number;
      afterFilteringSize: number;
      afterRelinkingSize: number;
    }[];
  };
};

export type PlaylistState = {
  state: "idle" | "saving" | "saved" | "loading" | "success" | "error" | "refreshing" | "refreshed";
  playlist?: Playlist;
};

export function useTrackRecommendations() {
  const [songRecommendation, setSongRecommendation] = useState<SongRecommendation>();
  const [songLyrics, setSongLyrics] = useState<string>("loading");
  const [playlist, setPlaylist] = useState<PlaylistState>({ state: "idle" });
  const [recommendationState, setRecommendationState] = useState({
    fetching: false,
    fetchNext: false,
    nextTrackId: "",
  });

  const { toast } = useToast();
  const router = useRouter();
  const { client } = useSpotify();

  // Memoized function to generate params for recommendations
  const generateRecommendationParams = useMemo(() => (track: Track) => {
    return {
      seed_tracks: [track.id],
      limit: 20,
      // Add additional params based on the track's audio features if desired
    };
  }, []);

  // Get track recommendation
  const getRecommendation = useCallback(async (track: Track) => {
    if (!client) return;
    
    setRecommendationState((state) => ({ ...state, fetching: true }));

    try {
      // In a real implementation, we would use the cached client to get recommendations
      // This appears to be a placeholder in the original code
      // const results = await client.getRecommendations(generateRecommendationParams(track));
      
      // For now, we'll just use the placeholder implementation from the original code
      setSongRecommendation({
        source: track,
        recommendation: { tracks: [track], seeds: [] },
      });
    } catch (error) {
      console.error("Error getting recommendations:", error);
      toast({
        title: "Error",
        description: "Failed to get song recommendations. Please try again.",
      });
    } finally {
      setRecommendationState({
        fetching: false,
        fetchNext: false,
        nextTrackId: "",
      });
    }
  }, [client, toast]);

  const refreshRecommendation = useCallback(async () => {
    if (!songRecommendation?.source || !client) return;
    
    try {
      setPlaylist({ state: "refreshing" });
      // In a real implementation, we would call the recommendation API here
      // await getRecommendation(songRecommendation.source);
      toast({
        title: "Recommendation refreshed!",
        description: "Enjoy the new songs.",
      });
    } catch (error) {
      console.error("Refresh error:", error);
      toast({
        title: "Error",
        description: "Failed to refresh recommendations. Please try again.",
      });
    } finally {
      setPlaylist({ state: "refreshed" });
    }
  }, [songRecommendation, client, toast]);

  const savePlaylist = useCallback(async () => {
    if (!client) return;
    
    try {
      setPlaylist({ state: "loading" });
      const user = await client.getCurrentUserProfile();
      if (!songRecommendation || !user) return;
      
      const payload = {
        name: `Song Likes: ${songRecommendation?.source.name} - ${songRecommendation?.source.artists[0].name} [Generated by Song Symmetry]`,
        description: `Songs have similar vibe to the ${songRecommendation?.source.name}. Enjoy :)`,
        public: true,
      };
      
      const newPlaylist = await client.createPlaylist(user.id, payload);
      if (newPlaylist) {
        const uris = songRecommendation.recommendation.tracks.map(
          (track) => track.uri
        );
        await client.addItemsToPlaylist(newPlaylist.id, uris);
      }
      
      setPlaylist({ state: "success", playlist: newPlaylist });
    } catch (error) {
      setPlaylist({ state: "error" });
      console.error("Save playlist error:", error);
      toast({
        title: "Error",
        description: "Failed to save playlist. Please try again.",
      });
    }
  }, [client, songRecommendation, toast]);

  const findSimilarSongs = useCallback((trackId: string) => {
    router.replace(`?trackId=${trackId}`);
    setRecommendationState({
      fetching: false,
      fetchNext: true,
      nextTrackId: trackId,
    });
    setSongLyrics("loading");
  }, [router]);

  const resetRecommendation = useCallback(() => {
    setSongRecommendation(undefined);
    setSongLyrics("");
  }, []);

  // Check user permissions for player features
  const checkUserPermission = useCallback(async () => {
    if (!client) return false;
    
    try {
      const user = await client.getCurrentUserProfile();
      if (!user) return false;
      
      if (user.product !== "premium") {
        toast({
          title: "Premium Required!",
          description: "Please upgrade to premium to use this feature.",
        });
        return false;
      }

      const playing = await client.getCurrentlyPlayingTrack();
      if (!playing) {
        toast({
          title: "No active device!",
          description: "Please play a song to use this feature.",
        });
        return false;
      }
      
      return true;
    } catch (error) {
      console.error(error);
      toast({
        title: "Error!",
        description: "Please try again later.",
      });
      return false;
    }
  }, [client, toast]);

  // Add song to queue
  const addSongToQueue = useCallback(async (trackUri: string) => {
    if (!client) return;
    
    const hasPermission = await checkUserPermission();
    if (!hasPermission) return;
    
    try {
      await client.addItemToPlaybackQueue(trackUri);
      toast({
        title: "Song added to queue 🥳!",
        description: "Enjoy the music.",
      });
    } catch (error) {
      console.error("Add to queue error:", error);
      toast({
        title: "Error adding to queue!",
        description: "Please try again later.",
      });
    }
  }, [client, checkUserPermission, toast]);

  // Add all songs to queue
  const addAllSongsToQueue = useCallback(async () => {
    if (!client) return;
    
    try {
      setPlaylist({ state: "saving" });

      const hasPermission = await checkUserPermission();
      if (!hasPermission) {
        setPlaylist({ state: "idle" });
        return;
      }
      
      const uris = songRecommendation?.recommendation.tracks.map(
        (track) => track.uri
      );
      
      if (!uris || uris.length === 0) {
        setPlaylist({ state: "idle" });
        return;
      }
      
      await Promise.all(
        uris.map(async (uri) => {
          return client.addItemToPlaybackQueue(uri);
        })
      );

      toast({
        title: "Songs added to queue 🥳!",
        description: "Enjoy the music.",
      });
      setPlaylist({ state: "saved" });
    } catch (error) {
      console.error("Error adding all to queue:", error);
      toast({
        title: "Error!",
        description: "Please try again later.",
      });
      setPlaylist({ state: "idle" });
    }
  }, [client, songRecommendation, checkUserPermission, toast]);

  // Fetch track if trackId is provided
  useEffect(() => {
    if (!recommendationState.nextTrackId || !client) return;
    
    (async () => {
      try {
        const track = await client.getTrack(recommendationState.nextTrackId);
        getRecommendation(track);
      } catch (error: any) {
        if (error.message?.includes("exceeded its rate limits")) {
          toast({
            title: "Rate limit exceeded!",
            description: "Please try again later.",
          });
          setRecommendationState({
            fetching: false,
            fetchNext: false,
            nextTrackId: "",
          });
        }
      }
    })();
  }, [recommendationState.nextTrackId, client, getRecommendation, toast]);

  // Fetch lyrics when song recommendation changes
  useEffect(() => {
    if (!songRecommendation) return;
    
    // Use a memory cache for lyrics to prevent redundant API calls
    const lyricsCache = new Map<string, string>();
    const cacheKey = `${songRecommendation.source.artists[0].name}-${songRecommendation.source.name}`;
    
    if (lyricsCache.has(cacheKey)) {
      setSongLyrics(lyricsCache.get(cacheKey) || "");
      return;
    }
    
    (async () => {
      try {
        const res = await fetch(
          `https://api.lyrics.ovh/v1/${encodeURIComponent(songRecommendation.source.artists[0].name)}/${encodeURIComponent(songRecommendation.source.name)}`
        );
        const resJson = await res.json();
        if (resJson.error) {
          setSongLyrics("Lyrics not found");
          lyricsCache.set(cacheKey, "Lyrics not found");
        } else {
          setSongLyrics(resJson.lyrics);
          lyricsCache.set(cacheKey, resJson.lyrics);
        }
      } catch (error) {
        setSongLyrics("not found");
        lyricsCache.set(cacheKey, "not found");
        toast({
          title: "Lyrics not found!",
          description: "Please try again later.",
        });
      }
    })();
  }, [songRecommendation, toast]);

  // Check for trackId in URL on initial load
  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    const trackId = params.get("trackId");
    if (trackId) {
      setRecommendationState({
        fetching: true,
        fetchNext: false,
        nextTrackId: trackId,
      });
    }
  }, []);

  return {
    songRecommendation,
    songLyrics,
    playlist,
    recommendationState,
    getRecommendation,
    refreshRecommendation,
    savePlaylist,
    findSimilarSongs,
    resetRecommendation,
    addSongToQueue,
    addAllSongsToQueue,
    setPlaylist
  };
}